### ISSUE TITLE
version 1.0?

### ISSUE THREAD

**Issue by ioquatix** [roja/system#5]
Hi, just wondering, this seems pretty stable, any reason why not to do a 1.0 release?

**Comment by RyanScottLewis** [comment]
Next stable release would be 0.2.0 (there are still planned features yet to be implemented.)

TODO list for next stable release:
- Tests.Hardly anything is actually tested and we need proof everything works on all combinations of all platforms, interpreters, and supported Ruby versions.
- Smarter implementation of system/interpreter specific conditions internally.
- Some methods are marked deprecated for 0.2.0 and need to be removed gracefully.
- CPU information would be nice but we could add this in 0.2.1
- I'd really like to rename System::Ruby to System::Interpreter

For now, if this gem works for ya, use it as is. It's been 2 years since any work as been done with this, so I'm not even sure how well this works now. It really needs a big overhaul before it's anywhere close to 1.0.0, let along the next stable release.

I'll try to work on this in my spare time.

**Comment by ioquatix** [comment]
I thought you might want to steal some of the ideas from https://github.com/celluloid/celluloid/blob/master/lib/celluloid/cpu_counter.rb

Also, if you give me commit access I'll work on this too. Let me know if you are interested. I'm also happy to just submit PRs but it is a bit more work..

**Comment by ioquatix** [comment]
Here is how they TEST the `CPUCounter` code: https://github.com/celluloid/celluloid/blob/master/spec/celluloid/cpu_counter_spec.rb

We could adopt something similar.

**Comment by ioquatix** [comment]
Bump..

**Comment by ioquatix** [comment]
Bump :)

**Comment by ioquatix** [comment]
Wondering if you'd be willing to transfer control of this gem to me so I can move it forward within your stated goals.

**Comment by RyanScottLewis** [comment]
I've actually begun work on this project again with an almost complete overhaul. Pretty soon, I'll push up a dev branch before the next gem release.

**Comment by ioquatix** [comment]
nice that would be great.

**Comment by ioquatix** [comment]
@RyanScottLewis Any update?

**Comment by ioquatix** [comment]
@roja @RyanScottLewis are you guys ever going to work on this again? Can you please give me access to this repo so I can work on it?

**Comment by ioquatix** [comment]
Dude, any update or is this the end?

**Comment by RyanScottLewis** [comment]
If you would like to contribute, please fork and open a pull request. I'm far too busy at the moment.

**Comment by ioquatix** [comment]
@RyanScottLewis Okay dude, sure, but the last thing you said was:

> I've actually begun work on this project again with an almost complete overhaul. Pretty soon, I'll push up a dev branch before the next gem release.

Was there any progress or was that just wishful thinking?

**Comment by RyanScottLewis** [comment]
That branch was pushed.

Edit: Correction, no it wasn't. Let me see what's up.

**Comment by RyanScottLewis** [comment]
Yeah, it was pushed the day of that comment. :thumbsup: Check out the `next` branch.

**Comment by ioquatix** [comment]
Okay, awesome, sorry that was not clear as there was no follow up here, e.g. "I've just pushed the branch next please check it out and submit a PR so we can make a new release, the following things still need work: x, y, z".

**Comment by RyanScottLewis** [comment]
Yeah, sorry about that! 

Things I see from skimming over the project:
- Tests. Need to come up with a solid plan for testing.
- I'd like to work on an adapter system as well rather than using the guard clauses and switch cases that we're using now.
- `System::Helpers::HasAttributes` could be replaced with `Aspect::HasAttributes`
- Anything relying on an external executable's output should probably check for it's existance or preferably not be used at all.
- There is a more than good chance that the `Dimensions` was a dumb idea.

Other than that, it's fair game.
